// this file is auto-generated
export default [
	["#_404", '_index_0', '/esm/_lib/_404/index_tsx.js'],
	["#components", '_components_md_1', '/esm/_lib/components_md.js'],
	["#configuration", '_index_md_2', '/esm/_lib/configuration/index_md.js'],
	["#deploy/firebase", '_firebase_md_3', '/esm/_lib/deploy/firebase_md.js'],
	["#deploy/github", '_github_md_4', '/esm/_lib/deploy/github_md.js'],
	["#deploy", '_index_md_5', '/esm/_lib/deploy/index_md.js'],
	["#esm", '_esm_md_6', '/esm/_lib/esm_md.js'],
	["#faq", '_faq_md_7', '/esm/_lib/faq_md.js'],
	["#fetch", '_fetch_md_8', '/esm/_lib/fetch_md.js'],
	["#getting-started", '_getting_started_md_9', '/esm/_lib/getting-started_md.js'],
	["#how-it-works", '_how_it_works_md_10', '/esm/_lib/how-it-works_md.js'],
	["#", '_index_md_11', '/esm/_lib/index_md.js'],
	["#item", '_item_12', '/esm/_lib/item_tsx.js'],
	["#pages", '_pages_md_13', '/esm/_lib/pages_md.js'],
	["#pwa", '_pwa_md_14', '/esm/_lib/pwa_md.js'],
	["#references", '_references_md_15', '/esm/_lib/references_md.js'],
	["#routing", '_routing_md_16', '/esm/_lib/routing_md.js'],
	["#todo", '_todo_md_17', '/esm/_lib/todo_md.js'],
	["#web-components/html", '_html_html_18', '/esm/_lib/web-components/html_html.js'],
	["#web-components", '_index_md_19', '/esm/_lib/web-components/index_md.js'],
	["#web-components/tsx", '_tsx_20', '/esm/_lib/web-components/tsx_tsx.js'],
]
